apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secrets
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.secrets.dbUsername | b64enc | quote }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  cors-allowed-origins: {{ .Values.secrets.corsAllowedOrigins | b64enc | quote }}
